language: node_js
sudo: required
node_js:
  - "8.11"
services:
  - docker
install:
  - npm install
before_script:
  - npm run package
script:
  - ./bin/unit-tests
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push lpwanserver/lpwanserver
  on:
    branch: master
