version: '2'

services:
  api-test:
    image: lpwanserver/api-test
    environment:
      - NODE_ENV=e2e
      - PORT=3200
      - db_file=data/demo_data/demo.sqlite3
    depends_on:
      - loraserver1
      - lora_appserver1
    ports:
      - '3200:3200'

  loraserver1:
    image: loraserver/loraserver:1
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - ./configuration/loraserver_1:/etc/loraserver

  lora_appserver1:
    image: loraserver/lora-app-server:1
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8081:8080
    volumes:
      - ./configuration/lora-app-server_1:/etc/lora-app-server

  postgresql:
    image: postgres:9.6-alpine
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb-demo:/docker-entrypoint-initdb.d

  redis:
    ports:
      - 6379
    image: redis:4-alpine
    volumes:
      - ../data/demo_data/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883