version: '2'

services:
  unit-test:
    image: lpwanserver/test
    environment:
    - NODE_ENV=e2e
    - PORT=3200
    ports:
    - '3200:3200'
    depends_on:
      - loraserver
      - loraserver1
      - lora_appserver
      - lora_appserver1
      - postgresql